import type { BoardCard } from "./types";

// World is in "world units" — cards positioned in a ~4000 x 3000 area
export const WORLD = { w: 4800, h: 3200, padding: 600 };

export const cards: BoardCard[] = [
  // INTRO — center
  {
    id: "intro",
    kind: "intro",
    x: 2200,
    y: 1300,
    rotation: -1.5,
    depth: 2,
    w: 520,
    h: 340,
  },

  // POLAROIDS near intro
  {
    id: "polaroid-karachi",
    kind: "polaroid",
    x: 1620,
    y: 1280,
    rotation: -6,
    depth: 1,
    caption: "home — karachi",
    emoji: "🌙",
    color: "#e9c79a",
  },
  {
    id: "polaroid-desk",
    kind: "polaroid",
    x: 2900,
    y: 1240,
    rotation: 5,
    depth: 1,
    caption: "the desk, 2am",
    emoji: "☕",
    color: "#c4623d",
  },
  {
    id: "polaroid-me",
    kind: "polaroid",
    x: 2250,
    y: 900,
    rotation: 2,
    depth: 2,
    caption: "haider, probably debugging",
    emoji: "🧑🏻‍💻",
    color: "#b88a3e",
  },

  // STICKY NOTES
  {
    id: "note-1",
    kind: "note",
    x: 1350,
    y: 900,
    rotation: -4,
    depth: 2,
    text: "design like you'll read it at 2am with tired eyes",
    author: "—h.",
    color: "yellow",
  },
  {
    id: "note-2",
    kind: "note",
    x: 3250,
    y: 1580,
    rotation: 6,
    depth: 2,
    text: "ship, then make it beautiful. never the other way.",
    color: "pink",
  },
  {
    id: "note-3",
    kind: "note",
    x: 1700,
    y: 1700,
    rotation: 3,
    depth: 2,
    text: "karachi · 05:00 UTC · coffee: black",
    color: "blue",
  },

  // QUOTE
  {
    id: "quote-1",
    kind: "quote",
    x: 2950,
    y: 820,
    rotation: -3,
    depth: 1,
    text: "a product is a frozen argument. design the argument first.",
  },

  // PROJECTS — scattered around center
  {
    id: "project-mochi",
    kind: "project",
    slug: "mochi",
    x: 600,
    y: 700,
    rotation: -4,
    depth: 0,
    title: "Mochi",
    tagline: "Design-system generator. Prompt → code → Figma.",
    year: "2026",
    stack: ["TypeScript", "AI"],
    accent: "terracotta",
    href: "https://github.com/haider0072",
  },
  {
    id: "project-audora",
    kind: "project",
    slug: "audora",
    x: 3700,
    y: 600,
    rotation: 4,
    depth: 0,
    title: "Audora",
    tagline: "Pro music player. FLAC, EQ, cloud sync.",
    year: "2025",
    stack: ["Next.js", "Web Audio"],
    accent: "ochre",
  },
  {
    id: "project-flowcraft",
    kind: "project",
    slug: "flowcraft",
    x: 700,
    y: 1600,
    rotation: 2,
    depth: 0,
    title: "FlowCraft",
    tagline: "AI sprite-sheet generator for 2D game characters.",
    year: "2025",
    stack: ["Next.js", "AI"],
    accent: "sage",
  },
  {
    id: "project-ember",
    kind: "project",
    slug: "ember",
    x: 3800,
    y: 1780,
    rotation: -3,
    depth: 0,
    title: "Ember",
    tagline: "Torrent player — stream while downloading.",
    year: "2024",
    stack: ["Flutter", "Dart"],
    accent: "terracotta",
  },
  {
    id: "project-trading",
    kind: "project",
    slug: "trading-bot",
    x: 1100,
    y: 2400,
    rotation: -5,
    depth: 0,
    title: "Trading Bot",
    tagline: "ML-driven automated crypto trading on Binance.",
    year: "2024",
    stack: ["Python", "ML"],
    accent: "ochre",
  },
  {
    id: "project-relay",
    kind: "project",
    slug: "relay",
    x: 3300,
    y: 2500,
    rotation: 3,
    depth: 0,
    title: "Relay",
    tagline: "Multi-channel marketing automation.",
    year: "2025",
    stack: ["Next.js", "NestJS"],
    accent: "sage",
  },
  {
    id: "project-wisesend",
    kind: "project",
    slug: "wisesend",
    x: 2250,
    y: 2550,
    rotation: -2,
    depth: 0,
    title: "WiseSend",
    tagline: "File transfer app — live on Play Store.",
    year: "2023",
    stack: ["Flutter"],
    accent: "terracotta",
  },

  // EXPERIENCE CARD
  {
    id: "experience",
    kind: "experience",
    x: 450,
    y: 1250,
    rotation: -2,
    depth: 1,
    w: 380,
    h: 460,
  },

  // SKILLS CARD
  {
    id: "skills",
    kind: "skills",
    x: 3950,
    y: 1150,
    rotation: 3,
    depth: 1,
    w: 380,
    h: 420,
  },

  // CONTACT
  {
    id: "contact",
    kind: "contact",
    x: 2200,
    y: 350,
    rotation: -1,
    depth: 2,
    w: 420,
    h: 220,
  },

  // STICKERS / DECOR
  {
    id: "sticker-arrow-1",
    kind: "sticker",
    x: 1900,
    y: 1180,
    rotation: -15,
    depth: 3,
    symbol: "↴",
    label: "that's me",
  },
  {
    id: "sticker-star",
    kind: "sticker",
    x: 1050,
    y: 650,
    rotation: 10,
    depth: 3,
    symbol: "✶",
  },
  {
    id: "sticker-heart",
    kind: "sticker",
    x: 3600,
    y: 900,
    rotation: -8,
    depth: 3,
    symbol: "❤",
  },
  {
    id: "sticker-flower",
    kind: "sticker",
    x: 1500,
    y: 2200,
    rotation: 12,
    depth: 3,
    symbol: "✿",
  },
  {
    id: "sticker-spark",
    kind: "sticker",
    x: 3150,
    y: 2100,
    rotation: -6,
    depth: 3,
    symbol: "✦",
  },
  {
    id: "sticker-circle",
    kind: "sticker",
    x: 2700,
    y: 2050,
    rotation: 0,
    depth: 3,
    symbol: "○",
    label: "tap a project →",
  },
];
